DEF_OP(Add, (int)'+', '+') 
DEF_OP(Sub, (int)'-', '-')
DEF_OP(Mul, (int)'*', '*')
DEF_OP(Div, (int)'/', '/')

DEF_FUNC(Cos, 1, "cos")
DEF_FUNC(Sin, 2, "sin")
DEF_FUNC(Tan, 3, "tan")
DEF_FUNC(Asin, 4, "asin")
DEF_FUNC(Acos, 5, "acos")
DEF_FUNC(Sqrt, 6, "sqrt")
DEF_FUNC(Exp, 7, "exp")
DEF_FUNC(Ln, 8, "ln")
